### ISSUE TITLE
Stack corruption

### ISSUE THREAD

**Issue by jamesadevine** [lancaster-university/codal-core#103]
@mmoskal @finneyj 

I think we have a case of stack corruption with the most recent changes to the fiber scheduler, specifically when launching fibers from within a 2 deep fiber context:

```
#1  <signal handler called>
#2  0x00000000 in ?? ()
#3  0x0000483e in codal::JDControlService::timerCallback (this=0x200005d4 <cplay+1164>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/JACDAC/control/JDControlService.cpp:168
#4  0x0000416e in codal::MemberFunctionCallback::methodCall<codal::JDControlService> (
    object=<optimized out>, method=<optimized out>, e=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/./inc/core/MemberFunctionCallback.h:111
---Type <return> to continue, or q <return> to quit---
#5  0x00006bc2 in codal::MemberFunctionCallback::fire (this=this@entry=0x20000fd4, e=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/MemberFunctionCallback.cpp:48
#6  0x00006590 in async_callback (param=0x20000fa8)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:119
#7  0x00005b6c in codal::invoke (entry_fn=entry_fn@entry=0x64f5 <async_callback(void*)>, 
    param=param@entry=0x20000fa8)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/CodalFiber.cpp:621
#8  0x0000683e in codal::MessageBus::process (this=this@entry=0x200001b8 <cplay+112>, evt=..., 
    urgent=urgent@entry=false)
---Type <return> to continue, or q <return> to quit---
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:379
#9  0x000068e6 in codal::MessageBus::idle (this=0x200001b8 <cplay+112>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:288
#10 0x00006362 in codal::MemberFunctionCallback::methodCall<codal::MessageBus> (object=<optimized out>, 
    method=<optimized out>, e=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/./inc/core/MemberFunctionCallback.h:111
#11 0x00006bc2 in codal::MemberFunctionCallback::fire (this=this@entry=0x20000dfc, e=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/MemberFunctionCallback.cpp:48
---Type <return> to continue, or q <return> to quit---
#12 0x00006590 in async_callback (param=0x20000dd0)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:119
#13 0x00006834 in codal::MessageBus::process (this=this@entry=0x200001b8 <cplay+112>, evt=..., 
    urgent=urgent@entry=true)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:377
#14 0x00006854 in codal::MessageBus::queueEvent (this=0x200001b8 <cplay+112>, evt=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/MessageBus.cpp:164
#15 0x000068c2 in codal::MessageBus::send (this=<optimized out>, evt=...)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/drivers/Mess---Type <return> to continue, or q <return> to quit---
ageBus.cpp:331
#16 0x00006936 in codal::Event::fire (this=0x20007fd4, this@entry=0x200001b8 <cplay+112>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/types/Event.cpp:126
#17 codal::Event::Event (this=this@entry=0x20007fd4, mode=codal::CREATE_AND_FIRE, value=<optimized out>, 
    source=<optimized out>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/types/Event.cpp:70
#18 0x0000695c in codal::Event::Event (this=0x20007fd4, source=<optimized out>, value=<optimized out>, 
    mode=<optimized out>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/types/Event.cpp:69
---Type <return> to continue, or q <return> to quit---
#19 0x0000586a in codal::idle ()
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/CodalFiber.cpp:966
#20 0x00005be2 in codal::idle_task ()
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/CodalFiber.cpp:989
#21 0x00005bd8 in codal::launch_new_fiber_param (ep=<optimized out>, cp=<optimized out>, 
    pm=<optimized out>)
    at /Users/James/Desktop/VM/jacdac-usb/jacdac-cplay-usb-driver/libraries/codal-core/source/core/CodalFiber.cpp:673
```

The xpsr, lr, psp values point to stack corruption according to my workings:
```
(gdb) print/x $xpsr
$6 = 0x1000003
(gdb) print $lr
$7 = (void (*)()) 0xfffffff9
(gdb) print $psp
$8 = (void *) 0xd464db9c
(gdb) print/x $control
$9 = 0x0
```

My simple, reproducible test is the following C++:

```cpp
#include "CircuitPlayground.h"
#include "JDTestService.h"
#include "CodalDmesg.h"

CircuitPlayground cplay;
JDTestService test("T", HostService);

void send_event()
{
    while(1)
    {
        cplay.sleep(20);
        Event(0xBEEF,0xBEEF);
    }
}

int main()
{
    cplay.jacdac.start();

    int state = 0;
    while(1)
    {
        cplay.io.led.setDigitalValue(state);
        fiber_sleep(500);
        state = !state;
    }
}
```

With the CodalConfig option `DEVICE_FIBER_USER_DATA` enabled, the program hardfaults after two LED blinks, with it disabled the LED blinks continuously.

Of course it's more likely I'm doing something weird in my JACDAC code, but from my inspections the device hard faults on a function call suggesting something more sinister.

**Comment by jamesadevine** [comment]
Hmmm, I've just re-enabled DEVICE_FIBER_USER_DATA, and everything is a-ok... curious!
